<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMlllSLE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMlllSLE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMlllSLE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMlllSLE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMlllSLE\App_KernelDevDebugContainer([
    'container.build_hash' => 'MlllSLE',
    'container.build_id' => '29d0c168',
    'container.build_time' => 1677825550,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMlllSLE');
