<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNkcGf7G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNkcGf7G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNkcGf7G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNkcGf7G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNkcGf7G\App_KernelDevDebugContainer([
    'container.build_hash' => 'NkcGf7G',
    'container.build_id' => '9b5c8ec6',
    'container.build_time' => 1677753283,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNkcGf7G');
