<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin_index' => [[], ['_controller' => 'App\\Controller\\AdminController::test2'], [], [['text', '/admin/test2']], [], [], []],
    'app_api' => [[], ['_controller' => 'App\\Controller\\ApiController::index'], [], [['text', '/api/']], [], [], []],
    'app_hoangtest_index' => [[], ['_controller' => 'App\\Controller\\HoangTestController::test'], [], [['text', '/hoangtest/test']], [], [], []],
    'app_hoangtest2_index' => [[], ['_controller' => 'App\\Controller\\HoangTestController::test2'], [], [['text', '/hoangtest/test2']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/']], [], [], []],
    'app_user_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/user/new']], [], [], []],
    'app_user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'app_user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'app_user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'user_edit_roles' => [['id'], ['_controller' => 'App\\Controller\\UserController::editRoles'], [], [['text', '/edit-roles'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user/users']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'hoang_test' => [[], ['_controller' => 'App\\Controller\\HoangTestController::index'], [], [['text', '/hoangtest']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], [], []],
];
